require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.7
  EnabledByDefault: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Layout/ClassStructure:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/ConstantVisibility:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Bundler/GemComment:
  Enabled: false
